import { lazy, ComponentType } from "react";

interface FigureRoute {
  id: string;
  component: React.LazyExoticComponent<ComponentType>;
  title: string;
}

export const figures: FigureRoute[] = [
  { id: "fig-01", component: lazy(() => import("./figures/fig-01-component-decision-flow")), title: "コンポーネント化の判断フロー" },
  { id: "fig-02", component: lazy(() => import("./figures/fig-02-three-layer-architecture")), title: "Feature-Sliced Design の3層構造" },
  { id: "fig-03", component: lazy(() => import("./figures/fig-03-generic-vs-domain")), title: "汎用とドメインの依存関係" },
  { id: "fig-04", component: lazy(() => import("./figures/fig-04-slot-pattern-button")), title: "Button のスロット構造" },
  { id: "fig-05", component: lazy(() => import("./figures/fig-05-toggle-vs-switch-bad-good")), title: "直交性: まとめた場合 vs 分けた場合" },
  { id: "fig-06", component: lazy(() => import("./figures/fig-06-shared-color-tokens")), title: "セマンティックカラートークンの共有" },
  { id: "fig-07", component: lazy(() => import("./figures/fig-07-ui-state-transitions")), title: "UIの5つの状態と遷移" },
  { id: "fig-08", component: lazy(() => import("./figures/fig-08-width-behaviors")), title: "Fill / Hug / Fixed の3パターン" },
  { id: "fig-09", component: lazy(() => import("./figures/fig-09-svg-vs-asset-decision")), title: "コード実装かアセット埋め込みか" },
  { id: "fig-10", component: lazy(() => import("./figures/fig-10-article-knowledge-hierarchy")), title: "本書の構成と知識の積み上げ" },
  { id: "fig-11", component: lazy(() => import("./figures/fig-11-radix-dialog-vs-alertdialog")), title: "Radix Dialog vs AlertDialog" },
  { id: "fig-12", component: lazy(() => import("./figures/fig-12-mui-chip-vs-badge")), title: "MUI Chip vs Badge" },
  { id: "fig-13", component: lazy(() => import("./figures/fig-13-antd-tag-vs-badge")), title: "Ant Design Tag vs Badge" },
  { id: "fig-14", component: lazy(() => import("./figures/fig-14-radix-select-dropdown-context")), title: "Radix Select / DropdownMenu / ContextMenu" },
  { id: "fig-15", component: lazy(() => import("./figures/fig-15-radix-toggle-vs-switch-rendered")), title: "Radix Toggle vs Switch" },
  { id: "fig-16", component: lazy(() => import("./figures/fig-16-chakra-badge-tag-colorscheme")), title: "Chakra Badge / Tag colorScheme" },
  { id: "fig-17", component: lazy(() => import("./figures/fig-17-property-types-explanation")), title: "プロパティの型: Figma とコードの対応" },
  { id: "fig-18", component: lazy(() => import("./figures/fig-18-figma-property-panel-mockup")), title: "Figma パネルとコードの対応" },
  { id: "fig-19", component: lazy(() => import("./figures/fig-19-padding-vs-margin")), title: "padding vs margin の責任分離" },
  { id: "fig-20", component: lazy(() => import("./figures/fig-20-premature-abstraction-before-after")), title: "早すぎる共通化の罠" },
  { id: "fig-21", component: lazy(() => import("./figures/fig-21-icon-library-vs-custom")), title: "既存ライブラリ vs 独自アイコン" },
  { id: "fig-22", component: lazy(() => import("./figures/fig-22-component-lifecycle-timeline")), title: "コンポーネントのライフサイクル" },
  { id: "fig-23", component: lazy(() => import("./figures/fig-23-single-source-of-truth")), title: "間接化: 1箇所の変更がすべてに届く" },
  { id: "fig-24", component: lazy(() => import("./figures/fig-24-separation-of-concerns")), title: "カプセル化: 3つの分離レイヤー" },
  { id: "fig-25", component: lazy(() => import("./figures/fig-25-build-strategy-spectrum")), title: "構築戦略の4パターン" },
  { id: "fig-26", component: lazy(() => import("./figures/fig-26-naming-explosion")), title: "命名: 組み合わせの爆発" },
  { id: "fig-27", component: lazy(() => import("./figures/fig-27-safe-vs-breaking-change")), title: "安全な変更と破壊的変更" },
  { id: "fig-28", component: lazy(() => import("./figures/fig-28-orthogonality-matrix")), title: "直交性マトリクス" },
  { id: "fig-29", component: lazy(() => import("./figures/fig-29-interaction-states")), title: "インタラクション状態" },
  { id: "fig-30", component: lazy(() => import("./figures/fig-30-currentcolor-svg")), title: "SVGの色制御: currentColor" },
  { id: "fig-31", component: lazy(() => import("./figures/fig-31-design-dimensions")), title: "コンポーネント設計の8つの観点" },
  { id: "fig-32", component: lazy(() => import("./figures/fig-32-generic-domain-boundary")), title: "汎用かドメインか: 視点で答えが変わる" },
  { id: "fig-33", component: lazy(() => import("./figures/fig-33-string-edge-cases")), title: "String型: テキストの振る舞い6パターン" },
  { id: "fig-34", component: lazy(() => import("./figures/fig-34-array-states")), title: "Array型: リストの4つの状態" },
  { id: "fig-35", component: lazy(() => import("./figures/fig-35-partial-state-fallback")), title: "Partial State: データ欠損時のフォールバック" },
  { id: "fig-36", component: lazy(() => import("./figures/fig-36-required-vs-optional")), title: "必須と任意: デフォルト値で使いやすさが決まる" },
  { id: "fig-37", component: lazy(() => import("./figures/fig-37-figma-vs-code-props")), title: "条件付き表示: Figmaでは2つ、コードでは1つ" },
  { id: "fig-38", component: lazy(() => import("./figures/fig-38-divider-placement")), title: "区切り線: コンポーネントに含めるか、親が制御するか" },
  { id: "fig-39", component: lazy(() => import("./figures/fig-39-path-dependency")), title: "経路依存性: 初期の選択が未来を縛る" },
  { id: "fig-40", component: lazy(() => import("./figures/fig-40-atomic-design-layers")), title: "Atomic Design: 5つの階層" },
  { id: "fig-41", component: lazy(() => import("./figures/fig-41-naming-degradation")), title: "慣習: ルールの有無が半年後の品質を決める" },
  { id: "fig-42", component: lazy(() => import("./figures/fig-42-boolean-contradiction")), title: "Boolean の矛盾: 2つのトグルより1つの Enum" },
  { id: "fig-43", component: lazy(() => import("./figures/fig-43-detach-alternatives")), title: "既存コンポーネントで実現できないとき: 4つの選択肢" },
  { id: "fig-44", component: lazy(() => import("./figures/fig-44-retrofit-steps")), title: "後発導入: 稼働中プロダクトへの3ステップ" },
  { id: "fig-45", component: lazy(() => import("./figures/fig-45-number-type")), title: "Number型: 数値の表示ルール" },
  { id: "fig-46", component: lazy(() => import("./figures/fig-46-date-type")), title: "Date型: 日付の表示形式と設計判断" },
  { id: "fig-47", component: lazy(() => import("./figures/fig-47-object-type")), title: "Object型: 個別の値 vs データのまとまり" },
  { id: "fig-48", component: lazy(() => import("./figures/fig-48-element-type")), title: "Element型（スロット）: 差し込み口で中身を自由に" },
  { id: "fig-49", component: lazy(() => import("./figures/fig-49-icon-name-lookup")), title: "ファイル個別管理 vs ライブラリによる名前呼び出し" },
  { id: "fig-50", component: lazy(() => import("./figures/fig-50-configuration-vs-composition")), title: "Configuration vs Composition: 設定の山か、組み合わせか" },
  { id: "fig-51", component: lazy(() => import("./figures/fig-51-ecosystem-lifecycle")), title: "デザインシステムの進化サイクル" },
  { id: "fig-52", component: lazy(() => import("./figures/fig-52-mental-model-sync")), title: "メンタルモデルの同期: Figma・コード・認知の一致" },
  { id: "fig-53", component: lazy(() => import("./figures/fig-53-constraint")), title: "制約: 選択肢を絞り、判断の負荷を下げる" },
  { id: "fig-54", component: lazy(() => import("./figures/fig-54-composition")), title: "合成: 小さな部品を組み合わせて大きなUIを構築する" },
  { id: "fig-55", component: lazy(() => import("./figures/fig-55-button-complexity")), title: "ボタンの複雑さ: シンプルに見えて設計判断の山" },
  { id: "fig-58", component: lazy(() => import("./figures/fig-58-naming-patterns")), title: "プロパティ命名: 4つの判断パターン" },
  { id: "fig-56", component: lazy(() => import("./figures/fig-56-library-component-samples")), title: "汎用ライブラリのコンポーネント例" },
  { id: "fig-57", component: lazy(() => import("./figures/fig-57-headless-ui-components")), title: "Headless UI: Listbox / Combobox / Menu" },
  { id: "fig-59", component: lazy(() => import("./figures/fig-59-generic-components")), title: "汎用コンポーネントの例" },
  { id: "fig-60", component: lazy(() => import("./figures/fig-60-domain-components")), title: "ドメインコンポーネントの例" },
  { id: "fig-61", component: lazy(() => import("./figures/fig-61-semantic-color-naming")), title: "色のセマンティクス: 見た目ではなく役割で名付ける" },
  { id: "fig-62", component: lazy(() => import("./figures/fig-62-array-concept")), title: "配列: 同じテンプレートに異なるデータを流し込む" },
  { id: "fig-63", component: lazy(() => import("./figures/fig-63-object-concept")), title: "オブジェクト: 複数の値をひとかたまりで渡す" },
];

export function getFigureById(id: string) {
  return figures.find((f) => f.id === id);
}
